default: &default
  adapter: postgresql
  pool: 5
development:
  <<: *default
  database: cantik_mart
  username: postgres
  password: postgres

test:
  <<: *default
  database: cantik_mart
  username: postgres
  password: postgres

production:
  adapter: postgresql
  pool: <%= ENV['RAILS_MAX_THREADS'].to_i + 2 %>
  database: cantik_mart
  username: postgres
  password: postgres
  timeout: 5000
