default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: cantik_mart_test
  username: postgres
  password: postgres

test:
  <<: *default
  database: cantik_mart_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: cantik_mart_test
  username: postgres
  password: postgres
