default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: cantik_mart
  username: postgres
  password: postgres

test:
  <<: *default
  database: cantik_mart
  username: postgres
  password: postgres

production:
  <<: *default
  host: localhost
  database: app-dev
  username: user
